name: Linux release build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  Linux-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: ${{github.workspace}}/scripts/build.sh ${{env.BUILD_TYPE}}
    
    - name: Run smoke tests
      run: ${{github.workspace}}/scripts/smoke_tests.sh